[package]
name = "day3"
version = "0.1.0"
authors = ["Dominik Stanojevic <dominik.stanojevic@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
